### ISSUE TITLE
"Your project" box has another height if no description provided

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/vpm#100]
### Describe the bug

For "pre-new VPM" packages there is no description (yet). and this kind of package has another height than new packages, submitted after a new VPM release.

### Expected Behavior

All 3 boxes have the same size

### Current Behavior

Package without description has smaller height for box

![image](https://github.com/vlang/vpm/assets/36485221/74f37b81-f1ba-4686-8d8f-f8545a05f1c1)

### Reproduction Steps

You need to have a package without a description somehow

### Possible Solution

@Casper64 

### Additional Information/Context

This bug is not a high priority since all submitted packages from now on will have a description

### V version

not related

### Environment details (OS name and version, etc.)

not related

**Comment by Casper64** [comment]
I will make the boxes a fixed height and add text overflow so the the description will always fit.
