### ISSUE TITLE
Proper Sorting Of Most Downloaded On VPM Site

### ISSUE THREAD

**Issue by Wajinn** [vlang/vpm#106]
### Describe the feature

For "Most Downloaded" it should show most to least (similar to "Browse Packages").  At this time, it appears backwards or non-working.

### Use Case

Looks better for the website and V community, that their VPM page is displaying things properly.

### Proposed Solution

Fix order of which modules are shown on "Most Downloaded".

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by alfu32** [comment]
so I fixed it,
Pull request ?

**Comment by medvednikov** [comment]
Yes, thanks,

**Comment by ArtemkaKun** [comment]
Fixed in #111
