### ISSUE TITLE
Update package a name / description

### ISSUE THREAD

**Issue by ttytm** [vlang/vpm#109]
### Describe the feature

Allow to update a submitted packaged. 

### Use Case

Name changes, Spelling issues.

Trying to re-submit a package in such cases currently results in `This URL has already been submitted`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.0 5ecbfb7.d4bedeb

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 5ecbfb7.d4bedeb
OS: linux, Pop!_OS 22.04 LTS
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

getwd: /home/turiiya/Dev/vlang/webview/emoji-picker
vexe: /home/turiiya/Dev/vlang/v/v
vexe mtime: 2023-07-25 12:58:56

vroot: OK, value: /home/turiiya/Dev/vlang/v
VMODULES: OK, value: /home/turiiya/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.28-81-gd4bedeba-dirty (11 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by ArtemkaKun** [comment]
Fixed in #111

**Comment by ttytm** [comment]
Nice thank you @ArtemkaKun !

**Comment by ArtemkaKun** [comment]
All credits go to @Terisback
