### ISSUE TITLE
Ability to manage modules, duplicates detection, documentation improvements

### ISSUE THREAD

**Issue by 1ace** [vlang/vpm#12]
Hi,

Not finding `sdl` in the list, I submitted https://github.com/vlang/sdl but it appeared as `1ace.sdl`, which was not my intention (as I obviously didn't write it).

Looking through the list again, I can see that https://github.com/vlang/sdl is actually present, but listed under @medvednikov's name, as `medvednikov.sdl`.

Please:
- [ ] delete my incorrect submission
- [ ] promote @medvednikov's `medvednikov.sdl` as the official `sdl`
- [ ] detect duplicate submissions (just checking the URL would get us 90% of the way there)
- [ ] provide a way to manage (at least remove) one's own submissions
- [ ] write at least one sentence on https://vpm.vlang.io/new to indicate that the module name submitted will be namespaced under the current user, and until there's a way to remove a submission this should also be mentioned there :)

Sorry for the multi-item issue, but these are all related and I think grouping them gives them context and makes more sense.

Thanks!

**Comment by ArtemkaKun** [comment]
Implemented in #111
