### ISSUE TITLE
Cannot add module to vpm

### ISSUE THREAD

**Issue by perry-mitchell** [vlang/vpm#13]
Hi!

Have been eyeing-off vlang for a long while, and finally decided to contribute my first module. I'm trying to submit it via the [vpm new page](https://vpm.vlang.io/new), but logging in to github doesn't get me anywhere:

![image](https://user-images.githubusercontent.com/3869469/94011042-6f803a00-fdaf-11ea-8c13-575c195c7c27.png)

I did log in and grant vlang access, but after that nothing.. Refreshing the page shows the same emptiness. No errors in console.

_Apologies if this is not the correct place for such an issue!_

EDIT: The module I'm trying to submit is [this one](https://github.com/perry-mitchell/logupdate)..

**Comment by OGoodness** [comment]
Any update on this?

**Comment by joao2391** [comment]
I think this issue was fixed. Today I submited my module successfully
