### ISSUE TITLE
vpm abandoned?

### ISSUE THREAD

**Issue by danawoodman** [vlang/vpm#26]
As a new V user, seeing the state of affairs of vpm makes me question adopting V as a language.

Not to be harsh, but the UI looks unprofessional and lacks even basic features. A small list of things missing:

- No description of the purpose of vpm
- Bad SEO: no page title or description
- Detail pages show nothing helpful (no description, README contents, version info, download stats, or dependency/version history, etc)
  - These details are critical for someone to know which package to use and to learn more before installing
- No support for organization/team management
  - Important for organization adoption
- No search
- Not responsive

Is this a project you're looking for collaborators on?

I believe having a package manager to compete with crates/npm is necessary for V to gain adoption and I'd be happy to help if contributing.

**Comment by danawoodman** [comment]
It appears at least one effort started for a redesign but it died out: https://github.com/vlang/vpm/pull/16

**Comment by sanathusk** [comment]
> It appears at least one effort started for a redesign but it died out: #16

The redesign is still happening, you could track https://github.com/Terisback/vpm for recent progress and to contribute.

**Comment by sanathusk** [comment]
The redesign code has been merged into the main branch, hopefully will go live soon.

**Comment by sanathusk** [comment]
@spytheman I think we can close the issue.
