### ISSUE TITLE
https://vpm-beta.vlang.io the V svg logo  is not visisble

### ISSUE THREAD

**Issue by sanathusk** [vlang/vpm#30]
https://vpm-beta.vlang.io the V svg logo that is supposed to be present in top left corner is not visible
![Screenshot 2023-04-08 at 2 34 24 PM](https://user-images.githubusercontent.com/19380158/230713302-f0ebf00d-1594-4532-a46a-bf004a0a23b2.png)

**Comment by ArtemkaKun** [comment]
Hi @sanathusk can you confirm that this issue still exists for you? On Firefox, Linux I have logo of VPM here as expected.

**Comment by Delta456** [comment]
The `.svg` logo is displayed on Windows, and Google Chrome.

![image](https://user-images.githubusercontent.com/28479139/236691868-2d4c78f5-7d3a-4afa-8230-1586ae9b9af8.png)
