### ISSUE TITLE
Some users reports problems with login

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/vpm#38]
Some users have login problems on Safari and Firefox browsers.

```
I did authorize the app and it still says "Log in via Github" when a want to submit a package
```

The problem seems not to be so trivial because I use Firefox on both PC and mobile and can log in on both devices.

**Comment by alfu32** [comment]
The same on chrome/iOS and chrome/Ubuntu.
It started at least 2 weeks ago when I tried logging in for the first time.

**Comment by medvednikov** [comment]
should be fixed now

**Comment by alfu32** [comment]
firefox/ubuntu                               ........... Working
chrome,firefox,edge,safary/iOS   ............Not working (I'm redirected  to vpm.vlang.io immediately after logging in to github.com without being presented with the list of permissions )

**Comment by ArtemkaKun** [comment]
Since no more cases were reported, I decided to close this issue
