### ISSUE TITLE
Edit module page

### ISSUE THREAD

**Issue by medvednikov** [vlang/vpm#4]
Update name, url, description, etc.

**Comment by thecodrr** [comment]
I have all the UIs and the functionality done. I will start making PRs for review etc. I didn't add any migrations so I might need help with that.

Also, @spytheman and me were thinking that module submission and editting should be through the CLI like in npm so we can easily handle repo links, updates, versioning etc. etc.

**Comment by ArtemkaKun** [comment]
I'm not sure if module page on a new version of VPM looks like expected
![image](https://user-images.githubusercontent.com/36485221/236690779-af7def2e-5107-4d8b-abcd-501a706090e7.png)

Probably we should close this issue or update requirements.

**Comment by ArtemkaKun** [comment]
Implement in #111
