### ISSUE TITLE
The previous packages section was better.

### ISSUE THREAD

**Issue by walkingdevel** [vlang/vpm#97]
Earlier, I was able to see all the tabs at once, but now I have to switch between them, and 4/5 of the screen is unused. It doesn't make sense.

<img width="1254" alt="packages" src="https://github.com/vlang/vpm/assets/104449470/3c869fdf-d2f5-42a7-96ca-deec4b6ca6b0">

**Comment by ArtemkaKun** [comment]
I didn't know we have tabs on PC version as well. I like them on mobile, but on PC they look strange indeed. We should have old layout for these 3 categories on PC, and dropdown on mobile

**Comment by Casper64** [comment]
It may look empty now, but in time more information will be added like a description for the module or some other stats/buttons. I think having 3 tabs next to each other (maybe 2) would not fit and you would have to scroll a lot. 

It was already crammed on a smaller laptop when 3/2 tabs were next to each other.

**Comment by walkingdevel** [comment]
@medvednikov wanted the main page looks like crates.io, and I agree with him. Such changes should be made through discussions. I didn't see a screenshot of the new version until I visited the updated site.

<img width="968" alt="crates" src="https://github.com/vlang/vpm/assets/104449470/b8c7600c-1eaa-4bfb-89a3-2713d42bc1ae">

**Comment by Casper64** [comment]
It is on the discord vpm channel in the first of the 2 videos I sent and heard no feedback about the categories on laptop. I appreciate the feedback tho.

**Comment by walkingdevel** [comment]
Hmm, right. Sorry, I didn't notice these videos. Then I'm surprised that Alex agreed to these changes.

**Comment by walkingdevel** [comment]
Next time, it's probably worth attaching screenshots straight to the PR to make it clearer what changes it is making.

**Comment by medvednikov** [comment]
I personally don't mind either of those. But I tend to agree with you @walkingdevel.

Less space lost, and similar to what users expect (crates.io).

**Comment by Casper64** [comment]
Well alright guess that's settled then. Would you prefer a grid like layout (like your packages) or the previous layout where there were 3 long columns?

**Comment by ArtemkaKun** [comment]
Done in #111 , should be reviewed after deploy and closed if completed

**Comment by ArtemkaKun** [comment]
Fixed in #111
